name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
        env:
          CI: true

      - run: npm shrinkwrap

      - run: npm run build

      - name: npm auth
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: npm auth & publish
        run: npm publish --access public

